const { test } = require('node:test')
const assert = require('node:assert/strict')
const { Client } = require('@modelcontextprotocol/sdk/client/index.js')
const { InMemoryTransport } = require('@modelcontextprotocol/sdk/inMemory.js')
const { createServer } = require('../dist/tools.js')
const { settingsSchema } = require('../dist/safety.js')

test('host exceptions never expose credentials and oversized telemetry fails safely', async t => {
  const server = createServer({ getSelfPath: () => ({ value: 'x'.repeat(40000) }), getFeatures: () => { throw new Error('password=do-not-return-this') } }, settingsSchema.parse({ allowedHosts: ['localhost'] }))
  const client = new Client({ name: 'error-test', version: '1' })
  const [left, right] = InMemoryTransport.createLinkedPair()
  await server.connect(left); await client.connect(right)
  t.after(async () => { await client.close(); await server.close() })
  const result = await client.callTool({ name: 'list_plugins', arguments: {} })
  assert.equal(result.structuredContent.error.code, 'INTERNAL_ERROR')
  assert.ok(!JSON.stringify(result).includes('do-not-return-this'))
  const large = await client.callTool({ name: 'read_path', arguments: { path: 'navigation.position' } })
  assert.equal(large.structuredContent.error.code, 'RESULT_TOO_LARGE')
})
